---
title: MOFA
jupyter: 
  kernelspec:
    name: "Omic_Integration"
    language: "python"
    display_name: "Omic_Integration"
---
## Resumen
En este informe, se realiza una reducción de dimensionalidad utilizando MOFA (Multi-Omics Factor Analysis) sobre los conjuntos de datos principales.

Añadir al sistema al ruta al directorio base para importar módulos personalizados.
```{python}
import sys, os
sys.path.append(os.path.abspath(".."))
```

Importar librerías y módulos necesarios.
```{python}
import pandas as pd
import muon as mu
import mofax as mofa
import matplotlib.pyplot as plt
from src.mofa_utils import create_mudata
import src.data_utils as du
```

Crear el directorio para guardar los datos procesados.
```{python}
mdata = create_mudata(
    "M_biogeochemical_genes_clr",
    "M_metabolic_genes_clr",
    "M_taxa_order_clr",
    "M_taxa_phylum_clr",
)
mdata
```

Crear y carpeta para guardar modelos en caso de que no exista.
```{python}
MODEL_DIR = "../models/"
MODEL_PATH = f"{MODEL_DIR}mofa_model.hdf5"
if not os.path.exists(MODEL_DIR):
    os.makedirs(MODEL_DIR, exist_ok=True)
M_biogeochemical_genes = mdata.mod["biogeochemical_genes"]
M_metabolic_genes = mdata.mod["metabolic_genes"]
M_Taxa_order = mdata.mod["taxa_order"]
M_Taxa_phylum = mdata.mod["taxa_phylum"]
```

Construir modelo MOFA si no existe.
```{python}
if not os.path.exists(MODEL_PATH):
    mu.tl.mofa(
        mdata,
        use_obs="union",
        n_factors=20,
        likelihoods=["gaussian", "gaussian", "gaussian", "gaussian"],
        convergence_mode="slow",
        outfile=MODEL_PATH,
    )
model = mofa.mofa_model(MODEL_PATH)
```

Obtener matriz de factores y guardarla en un DataFrame.
```{python}
Z = model.get_factors()
Z_df = pd.DataFrame(Z)
Z_df.columns = [f"Factor_{i + 1}" for i in range(Z_df.shape[1])]
Z_df.index = mdata.obs_names
Z_df.head(3)
```

Guardar matriz de factores.
```{python}
MOFA_DATA_DIR = "../data/MOFA_dir/"
Z_df.to_csv(f"{MOFA_DATA_DIR}M_factors.csv")
```

Analizar la varianza explicada por cada factor y vista.
```{python}
variance_explained = model.get_r2()
variance_explained.drop(columns=["Group"], inplace=True)
variance_explained["Factor"] = variance_explained["Factor"].str.replace(
    r"Factor(\d{1})$", r"Factor0\1", regex=True
)
variance_explained_pivot = variance_explained.pivot(
    index="Factor", columns="View", values="R2"
)
variance_explained_pivot
```

Guardar la varianza explicada.
```{python}
variance_explained_pivot.to_csv(f"{MOFA_DATA_DIR}M_variance_explained.csv")
```

Visualizar la varianza explicada por cada factor y vista.
```{python}
plt.figure(figsize=(10, 6))
plt.imshow(variance_explained_pivot, aspect="auto", cmap="Blues")
plt.xticks(
    ticks=range(len(variance_explained_pivot.columns)),
    labels=variance_explained_pivot.columns,
    rotation=45,
)
plt.yticks(
    ticks=range(len(variance_explained_pivot.index)),
    labels=variance_explained_pivot.index,
)
plt.colorbar(label="R2 (%)")
plt.title("Variance Explained per Factor and View")
plt.tight_layout()
```

Obtener los pesos de las variables para cada vista.
```{python}
W = model.get_weights()

n_bio = M_biogeochemical_genes.n_vars
n_met = M_metabolic_genes.n_vars
n_order = M_Taxa_order.n_vars
n_phylum = M_Taxa_phylum.n_vars

idx_bio = slice(0, n_bio)
idx_met = slice(n_bio, n_bio + n_met)
idx_order = slice(n_bio + n_met, n_bio + n_met + n_order)
idx_phylum = slice(n_bio + n_met + n_order, n_bio + n_met + n_order + n_phylum)

W_bio = W[idx_bio, :]
W_met = W[idx_met, :]
W_order = W[idx_order, :]
W_phylum = W[idx_phylum, :]
```

Guardar los pesos de las variables para cada vista.
```{python}
pd.DataFrame(W_bio, index=M_biogeochemical_genes.var_names).to_csv(
    f"{MOFA_DATA_DIR}W_biogeochemical_genes.csv"
)
pd.DataFrame(W_met, index=M_metabolic_genes.var_names).to_csv(
    f"{MOFA_DATA_DIR}W_metabolic_genes.csv"
)
pd.DataFrame(W_order, index=M_Taxa_order.var_names).to_csv(
    f"{MOFA_DATA_DIR}W_taxa_order.csv"
)
pd.DataFrame(W_phylum, index=M_Taxa_phylum.var_names).to_csv(
    f"{MOFA_DATA_DIR}W_taxa_phylum.csv"
)
```

___

